name: Merge upstream

on:
  schedule:
    - cron: '32 9 8 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Create a pull request if updated
        id: pr
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Capchdo/rss-to-email/pulls \
            -f title='Merge upstream' \
            -f body='Relates-to: #1' \
            -f head='bdevos:main' \
            -f base='haobit' \
            -F maintainer_can_modify=false
        # Fork collaboration lacks permission, therefore we disable `maintainer_can_modify`.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        # We rely on GitHub to compare with the upstream.
        # If updated, a PR will be created.
        # If unchanged, the following error will occur.
        #     message: Validation Failed
        #     errors:
        #       - resource: PullRequest
        #         code: custom
        #         message: No commits between … and …
        #     documentation_url: …
        # GitHub is more intelligent than `git diff`,
        # and create-or-ignore is much simpler and more robust than detect-and-create.
      - if: ${{ steps.pr.outcome == 'failure' }}
        run: |
          echo "We are up to date with the upstream." >> "$GITHUB_STEP_SUMMARY"
